version: "3"

services:
  postgres:
    image: postgres:14
    container_name: lim-postgres
    environment:
      POSTGRES_USER: limadmin
      POSTGRES_PASSWORD: limpassword
      POSTGRES_DB: limdb
    ports:
      - "5432:5432"
    volumes:
      - lim-pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: lim-redis
    ports:
      - "6379:6379"
    volumes:
      - lim-redis:/usr/local/etc/redis

  registry:
    image: registry:2
    container_name: lim-registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - lim-registry-data:/var/lib/registry
    networks:
      - lim-network

volumes:
  lim-pgdata:
  lim-registry-data:
  lim-redis:

networks:
  lim-network:
    driver: bridge
